# Generated by Django 4.0.4 on 2022-05-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_engineer',
            field=models.BooleanField(default=False, verbose_name='engineer status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='moderator status'),
        ),
    ]
